makeandbake:ADMEnigma.cpp CSVReader.cpp BinCoder.cpp RLECoder.cpp DicCoder.cpp FORCoder.cpp DifCoder.cpp
	g++ ADMEnigma.cpp CSVReader.cpp BinCoder.cpp RLECoder.cpp DicCoder.cpp FORCoder.cpp DifCoder.cpp -o program.exe
	REM Compiled and ready to go! Please enter: program.exe with commands: Action Compression DataType Filename (output#, 0 for full)