makeandbake:ADMEnigma.cpp BinCoder.cpp
	g++ ADMEnigma.cpp BinCoder.cpp -o ADMEnigma.exe
	REM Compiled and ready to go! Please enter: ADMEnigma.exe with commands for: Action, Compression, DataType, Filename