makeandbake:ADMEnigma.cpp BinCoder.cpp
	g++ ADMEnigma.cpp BinCoder.cpp CSVReader.cpp CSVWriter.cpp -o program.exe
	REM Compiled and ready to go! Please enter: program.exe with commands: Action, Compression, DataType, Filename